apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: FILES_SERVICE_PORT_ENV
               valueFrom:
                 secretKeyRef:
                   name: smart-team-backend-files-production-config-secret
                   key: FILES_SERVICE_PORT_ENV
             - name: FILES_SERVICE_HOST_ENV
               valueFrom:
                 secretKeyRef:
                   name: smart-team-backend-files-production-config-secret
                   key: FILES_SERVICE_HOST_ENV
